name: Deploy Node.js to Cloud Run

permissions:
  id-token: write   # задължително за OIDC
  contents: read

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout на кода
      - name: Checkout code
        uses: actions/checkout@v3

      #  Unset стар JSON ключ (ако има)
      - name: Unset old credentials
        run: unset GOOGLE_APPLICATION_CREDENTIALS

      # Authenticate към GCP чрез WIF
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/478055754796/locations/global/workloadIdentityPools/github-pool/providers/githubidentityprovider"
          service_account: "studynodejsserviceaccount@study-nodejs-479620.iam.gserviceaccount.com"
          token_format: "access_token"   # важно за Cloud Build / Cloud Run
          project_id: "study-nodejs-479620"

      # 4️⃣ Debug (проверка на token и project)
      - name: Debug GCP auth
        run: |
          gcloud auth list
          gcloud config get-value project
          gcloud auth print-access-token

      # 5️⃣ Build & Deploy
      - name: Build & Deploy to Cloud Run
        run: |
          gcloud builds submit \
            --tag europe-west1-docker.pkg.dev/study-nodejs-479620/bisser-repo/nodejs-server:latest

          gcloud run deploy nodejs-server \
            --image europe-west1-docker.pkg.dev/study-nodejs-479620/bisser-repo/nodejs-server:latest \
            --region europe-west1 \
            --platform managed \
            --allow-unauthenticated